#!/usr/bin/env bash
# QuicData Ubuntu 22 standalone environment one-click deployment script
# Applicable scenario: Redis / PostgreSQL deployed separately, host only runs application processes
# Usage:
#   bash scripts/deploy-ubuntu.sh
#
# Supports environment variable presets (avoids interactive prompts):
#   DATABASE_URL=postgresql+psycopg://quicdata:quicdata@127.0.0.1:5432/quicdata
#   REDIS_URL=redis://127.0.0.1:6379/0
#   SECRET_KEY=xxx
#   QRDF_GIT_URL=...
#   QRDF_GIT_REF=develop

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND="$ROOT/backend"
ENV_FILE="$BACKEND/.env"
QRDF_ENV_FILE="$ROOT/deploy/qrdf.env"

_log() { echo "[$(date '+%H:%M:%S')] $*"; }
_fail() { echo "错误: $*" >&2; exit 1; }

# ---------- 1. System check ----------
_log "检查操作系统..."
if [[ -f /etc/os-release ]]; then
  # shellcheck disable=SC1091
  source /etc/os-release
  if [[ "$ID" != "ubuntu" ]]; then
    echo "警告: 当前不是 Ubuntu 系统 ($ID)，脚本按 Ubuntu 22 逻辑执行" >&2
  fi
fi

_log "检查 Python 版本..."
PYTHON="${PYTHON:-python3}"
if ! command -v "$PYTHON" &>/dev/null; then
  _fail "未找到 $PYTHON"
fi

PY_MAJOR=$("$PYTHON" -c 'import sys; print(sys.version_info.major)')
PY_MINOR=$("$PYTHON" -c 'import sys; print(sys.version_info.minor)')
if [[ "$PY_MAJOR" -lt 3 ]] || [[ "$PY_MAJOR" -eq 3 && "$PY_MINOR" -lt 10 ]]; then
  _fail "需要 Python 3.10+，当前为 ${PY_MAJOR}.${PY_MINOR}"
fi
_log "Python 版本: ${PY_MAJOR}.${PY_MINOR} ($($PYTHON -c 'import sys; print(sys.executable)'))"

# ---------- 2. Install system dependencies ----------
_log "安装系统依赖..."
sudo apt update
sudo apt install -y git "$PYTHON" "${PYTHON}-venv" "${PYTHON}-pip" curl

# ---------- 3. QRDF configuration ----------
if [[ ! -f "$QRDF_ENV_FILE" ]]; then
  _log "创建 QRDF 配置模板: $QRDF_ENV_FILE"
  cp "$ROOT/deploy/qrdf.env.example" "$QRDF_ENV_FILE"
  _log "请按需编辑 $QRDF_ENV_FILE 中的 QRDF_GIT_URL / QRDF_GIT_REF"
else
  _log "QRDF 配置已存在: $QRDF_ENV_FILE"
fi

# ---------- 4. Fetch QRDF SDK + install Python dependencies ----------
_log "执行 bootstrap（拉取 QRDF SDK + 安装依赖）..."
bash "$ROOT/deploy/bootstrap.sh"

# ---------- 5. Generate / write backend/.env ----------
if [[ ! -f "$ENV_FILE" ]]; then
  _log "创建 backend/.env..."

  # Prefer reading from environment variables, otherwise prompt interactively
  if [[ -z "${DATABASE_URL:-}" ]]; then
    read -r -p "PostgreSQL 连接串 [postgresql+psycopg://quicdata:quicdata@127.0.0.1:5432/quicdata]: " input
    DATABASE_URL="${input:-postgresql+psycopg://quicdata:quicdata@127.0.0.1:5432/quicdata}"
  fi

  if [[ -z "${REDIS_URL:-}" ]]; then
    read -r -p "Redis URL [redis://127.0.0.1:6379/0]: " input
    REDIS_URL="${input:-redis://127.0.0.1:6379/0}"
  fi

  if [[ -z "${SECRET_KEY:-}" ]]; then
    SECRET_KEY=$("$PYTHON" -c "import secrets; print(secrets.token_urlsafe(48))")
    _log "已自动生成 SECRET_KEY"
  fi

  # Extract host:port from Redis URL to construct Celery Broker/Backend
  REDIS_BASE="${REDIS_URL%/*}"
  CELERY_BROKER_URL="${REDIS_BASE}/1"
  CELERY_RESULT_BACKEND="${REDIS_BASE}/2"

  cat > "$ENV_FILE" <<EOF
# QuicData backend environment variables (generated by deploy-ubuntu.sh)
API_HOST=0.0.0.0
API_PORT=8000
SECRET_KEY=${SECRET_KEY}

DATABASE_URL=${DATABASE_URL}

REDIS_URL=${REDIS_URL}
CELERY_BROKER_URL=${CELERY_BROKER_URL}
CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
CELERY_CONCURRENCY=8

SCRATCH_ROOT=./runtime/scratch

# Provider-backed object storage (required; no local/cloud mirror fallback).
STORAGE_PROVIDER=${STORAGE_PROVIDER:-aliyun}
STORAGE_ENDPOINT=${STORAGE_ENDPOINT:-https://oss-cn-beijing.aliyuncs.com}
# Credentials are intentionally not written to backend/.env. Export
# STORAGE_ACCESS_KEY_ID and STORAGE_SECRET_ACCESS_KEY in the service manager
# environment (or use deploy/run-with-secrets.sh for container deployments).
OSS_BUCKET_RAW=${OSS_BUCKET_RAW:-quicstudio-prod-raw}
OSS_BUCKET_PROCESS=${OSS_BUCKET_PROCESS:-quicstudio-prod-process}
OSS_BUCKET_EXPORT=${OSS_BUCKET_EXPORT:-quicstudio-prod-export}
OSS_REGION=${OSS_REGION:-cn-beijing}
EOF

  _log ".env 已生成: $ENV_FILE"
else
  _log ".env 已存在，跳过生成: $ENV_FILE"
fi

# ---------- 6. Start services ----------
_log "启动 QuicData API + Worker..."
bash "$ROOT/scripts/start-all.sh" start

# ---------- 7. Health check ----------
_log "等待服务就绪..."
sleep 3

if curl -s http://127.0.0.1:8000/health >/dev/null 2>&1; then
  _log "健康检查通过:"
  curl -s http://127.0.0.1:8000/health | python3 -m json.tool
else
  _fail "健康检查失败，请查看日志: bash scripts/start-all.sh logs"
fi

_log "部署完成"
echo ""
echo "常用命令:"
echo "  查看状态: bash scripts/start-all.sh status"
echo "  查看日志: bash scripts/start-all.sh logs"
echo "  停止服务: bash scripts/start-all.sh stop"
echo "  访问地址: http://$(hostname -I 2>/dev/null | awk '{print $1}'):8000"
echo "  默认账号: admin@quicdata.com / admin123"
